spring.application.name=biblioteca

# MongoDB Atlas
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://fillipemateus_db_user:GKrQgaIOx7jsuDJf@cluster0.w26ogxa.mongodb.net/?appName=Cluster0}
spring.data.mongodb.database=${MONGODB_DB:biblioteca}

# Thymeleaf
spring.thymeleaf.cache=false

# Porta
server.port=8080

# Mensagens de erro
server.error.include-message=always
