spring.application.name=biblioteca

# MongoDB — URI carregada do arquivo .env na raiz do projeto
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017}
spring.data.mongodb.database=${MONGODB_DB:biblioteca}

# Thymeleaf
spring.thymeleaf.cache=false

# Porta
server.port=8080

# Mensagens de erro
server.error.include-message=always
